aufgabe3/config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get     'login'     =>  'sessions#new'
  post    'login'     =>  'sessions#create'
  delete  'logout'    =>  'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :email_changes, only: [:edit]

	root :to => "sessions#new"
end

aufgabe3/app/models/user.rb
class User < ActiveRecord::Base

  before_create :create_activation_digest
  attr_accessor :activation_token, :reset_token
  attr_accessor :email_change_token
  after_initialize :set_default_is_admin
	before_save { 
    self.email = email.downcase 
    self.email_to_verify = email_to_verify.downcase
  }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, 
                       length: { minimum: 6 },
                       if: :password
                  

  def start_activation
    update_attribute(:activation_started,    Time.zone.now)
  end

  def activate
    # check 30min threshold
		if (activation_started + 30.minutes).before? Time.zone.now
      destroy
			false
		else
    	update_attribute(:activated,    true)
  	  update_attribute(:activated_at, Time.zone.now)
			true
		end
  end

  def password_reset_expired?
    reset_started < 30.minutes.ago
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token),
                   reset_started: Time.zone.now)
  end

  def start_email_change
    self.email_change_token = User.new_token
    update_attribute(:email_change_digest, User.digest(email_change_token))
    update_attribute(:email_change_at, Time.zone.now)
  end

  def email_changed?
    email != email_to_verify
  end

  def email_change_expired?
    email_change_at < 30.minutes.ago
  end

  def execute_email_change
    update_attribute(:email, email_to_verify)
  end

 private

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def set_default_is_admin
    self.is_admin ||= false
  end

end

aufgabe3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_only_permission, only: [:index, :new, :create, :destroy]
  before_action :check_permission, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.start_activation
        UserMailer.account_activation(@user).deliver_now
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      user_dup = delete_password_if_blank(user_params)
      if @user.update_attributes(user_dup)
        msgs = []
        msgs << 'User was successfully updated.'
        if @user.email_changed?
          start_email_verification 
          msgs << 'Check up your new email.'
        end
        format.html { redirect_to @user, notice: msgs }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def delete_password_if_blank(user_params)
      user_dup = user_params.dup
      if user_params[:password].empty? && user_params[:password_confirmation].empty?
        user_dup.delete(:password) 
        user_dup.delete(:password_confirmation) 
      end
      user_dup
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      permitted_params = [:email, :password, :password_confirmation, :email_to_verify]
      permitted_params << :is_admin if current_user.is_admin? 
      params.require(:user).permit(*permitted_params)
    end

    def check_admin_only_permission
      if !logged_in? || !current_user.is_admin
        redirect_to login_path        
      end
    end

    # ensures
    #   - current_user is logged in
    #   - current_user is editing himself or is_admin
    def check_permission
      redirect_to login_path unless logged_in?
      redirect_to login_path unless current_user.is_admin || @user.id == current_user.id 
    end
    
    def start_email_verification
      @user.start_email_change
      UserMailer.email_change(@user).deliver_now
    end
end

aufgabe3/app/helpers/users_helper.rb
module UsersHelper
end

aufgabe3/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br>
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aufgabe3/app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email_to_verify, :value => @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Confirmation" %></br>
    <%= f.password_field :password_confirmation %>
  </div>
  <% if current_user.is_admin? %>
    <div class="field">
      <%= f.label :is_admin %><br>
      <%= f.check_box :is_admin %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aufgabe3/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Activated</th>
      <th>Is admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.activated %></td>
        <td><%= user.is_admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

aufgabe3/app/views/users/new.html.erb
<h1>New user</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Confirmation" %></br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br>
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

aufgabe3/app/views/users/show.html.erb
<p id="notice"><%= notice.join("</br>").html_safe if notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Is admin:</strong>
  <%= @user.is_admin %>
</p>

<p>
  <strong>Is activated:</strong>
  <%= @user.activated %>
</p>

<p>
  <strong>Activated At:</strong>
  <%= @user.activated_at %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %>
<% if current_user.is_admin? %>
  <%= link_to 'Back', users_path %>
<% end %>